#!/usr/bin/env tsx
/**
 * Auto-generate sidebars.ts from skills.ts
 *
 * This script reads ALL_SKILLS from src/data/skills.ts and generates
 * the complete sidebar structure with all skills organized by category.
 *
 * Run: npx tsx scripts/generate-sidebar.ts
 */

import { ALL_SKILLS } from '../src/data/skills';
import { writeFileSync } from 'fs';
import { join } from 'path';

// Group skills by category
const skillsByCategory = ALL_SKILLS.reduce((acc, skill) => {
  if (!acc[skill.category]) {
    acc[skill.category] = [];
  }
  acc[skill.category].push(skill);
  return acc;
}, {} as Record<string, typeof ALL_SKILLS>);

// Generate sidebar structure
const generateSidebar = () => {
  const categories = Object.keys(skillsByCategory);

  const categoryItems = categories.map(category => {
    const skills = skillsByCategory[category];
    const items = skills.map(skill => {
      // Extract the last part of the path (e.g., /docs/skills/skill_name -> skill_name)
      const skillPath = skill.path.split('/').pop();
      return `        'skills/${skillPath}'`;
    }).join(',\n');

    return `    {
      type: 'category',
      label: '${category}',
      collapsed: false,
      items: [
${items},
      ],
    }`;
  }).join(',\n');

  const sidebarContent = `import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Auto-generated sidebar from skills.ts
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 * Run: npx tsx scripts/generate-sidebar.ts
 *
 * This sidebar is automatically generated from src/data/skills.ts
 * to ensure it stays in sync with the skills gallery.
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'guides/claude-skills-guide',
        'guides/examples',
        'guides/skills-documentation',
      ],
    },
${categoryItems},
  ],
};

export default sidebars;
`;

  return sidebarContent;
};

// Write the generated sidebar
const sidebarPath = join(__dirname, '..', 'sidebars.ts');
const content = generateSidebar();
writeFileSync(sidebarPath, content, 'utf-8');

console.log('✅ Generated sidebars.ts successfully!');
console.log(`📊 Total skills: ${ALL_SKILLS.length}`);
console.log(`📁 Categories: ${Object.keys(skillsByCategory).length}`);
console.log('');
console.log('Category breakdown:');
Object.entries(skillsByCategory).forEach(([category, skills]) => {
  console.log(`  ${category}: ${skills.length} skills`);
});
