#!/usr/bin/env tsx
"use strict";
/**
 * Auto-generate sidebars.ts from skills.ts
 *
 * This script reads ALL_SKILLS from src/data/skills.ts and generates
 * the complete sidebar structure with all skills organized by category.
 *
 * Run: npx tsx scripts/generate-sidebar.ts
 */
Object.defineProperty(exports, "__esModule", { value: true });
var skills_1 = require("../src/data/skills");
var fs_1 = require("fs");
var path_1 = require("path");
// Group skills by category
var skillsByCategory = skills_1.ALL_SKILLS.reduce(function (acc, skill) {
    if (!acc[skill.category]) {
        acc[skill.category] = [];
    }
    acc[skill.category].push(skill);
    return acc;
}, {});
// Generate sidebar structure
var generateSidebar = function () {
    var categories = Object.keys(skillsByCategory);
    var categoryItems = categories.map(function (category) {
        var skills = skillsByCategory[category];
        var items = skills.map(function (skill) {
            // Extract the last part of the path (e.g., /docs/skills/skill_name -> skill_name)
            var skillPath = skill.path.split('/').pop();
            return "        'skills/".concat(skillPath, "'");
        }).join(',\n');
        return "    {\n      type: 'category',\n      label: '".concat(category, "',\n      collapsed: false,\n      items: [\n").concat(items, ",\n      ],\n    }");
    }).join(',\n');
    var sidebarContent = "import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';\n\n// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)\n\n/**\n * Auto-generated sidebar from skills.ts\n *\n * DO NOT EDIT THIS FILE MANUALLY!\n * Run: npx tsx scripts/generate-sidebar.ts\n *\n * This sidebar is automatically generated from src/data/skills.ts\n * to ensure it stays in sync with the skills gallery.\n */\nconst sidebars: SidebarsConfig = {\n  // Main documentation sidebar\n  tutorialSidebar: [\n    'intro',\n    {\n      type: 'category',\n      label: 'Guides',\n      collapsed: false,\n      items: [\n        'guides/claude-skills-guide',\n        'guides/examples',\n        'guides/skills-documentation',\n      ],\n    },\n".concat(categoryItems, ",\n  ],\n};\n\nexport default sidebars;\n");
    return sidebarContent;
};
// Write the generated sidebar
var sidebarPath = (0, path_1.join)(__dirname, '..', 'sidebars.ts');
var content = generateSidebar();
(0, fs_1.writeFileSync)(sidebarPath, content, 'utf-8');
console.log('✅ Generated sidebars.ts successfully!');
console.log("\uD83D\uDCCA Total skills: ".concat(skills_1.ALL_SKILLS.length));
console.log("\uD83D\uDCC1 Categories: ".concat(Object.keys(skillsByCategory).length));
console.log('');
console.log('Category breakdown:');
Object.entries(skillsByCategory).forEach(function (_a) {
    var category = _a[0], skills = _a[1];
    console.log("  ".concat(category, ": ").concat(skills.length, " skills"));
});
