import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Sidebar configuration for skills documentation.
 *
 * Skills with folders (containing index.md + references/) use autogenerated
 * sidebars to automatically include all sub-files.
 */

// Helper to create autogenerated sidebar for a skill folder
const skillFolder = (dirName: string) => ({
  type: 'category' as const,
  label: dirName.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '),
  link: { type: 'doc' as const, id: `skills/${dirName}/${dirName}` },
  items: [{ type: 'autogenerated' as const, dirName: `skills/${dirName}` }],
});

// Simple skill doc (no folder structure)
const skillDoc = (id: string) => `skills/${id}`;

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'guides/claude-skills-guide',
        'guides/prompt-learning-mcp',
        'guides/examples',
        'guides/skills-documentation',
      ],
    },
    {
      type: 'category',
      label: 'Council Archives',
      collapsed: false,
      items: [
        'council/index',
        'council/liaison-reports',
        'council/snapshots',
        'council/decisions',
      ],
    },
    {
      type: 'category',
      label: 'Orchestration & Meta',
      collapsed: false,
      items: [
        skillDoc('orchestrator'),
        skillFolder('agent_creator'),
        skillFolder('skill_coach'),
        skillFolder('skill_documentarian'),
        skillDoc('swift_executor'),
        skillFolder('automatic_stateful_prompt_improver'),
      ],
    },
    {
      type: 'category',
      label: 'Visual Design & UI',
      collapsed: false,
      items: [
        skillFolder('web_design_expert'),
        skillFolder('design_system_creator'),
        skillFolder('native_app_designer'),
        skillFolder('vaporwave_glassomorphic_ui_designer'),
        skillFolder('windows_3_1_web_designer'),
        skillDoc('typography_expert'),
        skillDoc('vibe_matcher'),
        skillFolder('interior_design_expert'),
        skillFolder('design_archivist'),
      ],
    },
    {
      type: 'category',
      label: 'Graphics, 3D & Simulation',
      collapsed: false,
      items: [
        skillFolder('metal_shader_expert'),
        skillDoc('vr_avatar_engineer'),
        skillFolder('physics_rendering_expert'),
        skillFolder('collage_layout_expert'),
        skillFolder('2000s_visualization_expert'),
      ],
    },
    {
      type: 'category',
      label: 'Audio & Sound Design',
      collapsed: false,
      items: [
        skillFolder('sound_engineer'),
        skillFolder('voice_audio_engineer'),
      ],
    },
    {
      type: 'category',
      label: 'Computer Vision & Image AI',
      collapsed: false,
      items: [
        skillDoc('clip_aware_embeddings'),
        skillFolder('photo_content_recognition_curation_expert'),
        skillFolder('event_detection_temporal_intelligence_expert'),
        skillFolder('photo_composition_critic'),
        skillFolder('color_theory_palette_harmony_expert'),
      ],
    },
    {
      type: 'category',
      label: 'Autonomous Systems & Robotics',
      collapsed: false,
      items: [
        skillFolder('drone_cv_expert'),
        skillFolder('drone_inspection_specialist'),
      ],
    },
    {
      type: 'category',
      label: 'Conversational AI & Bots',
      collapsed: false,
      items: [
        skillFolder('bot_developer'),
      ],
    },
    {
      type: 'category',
      label: 'Research & Strategy',
      collapsed: false,
      items: [
        skillDoc('research_analyst'),
        skillDoc('team_builder'),
        skillFolder('competitive_cartographer'),
        skillFolder('hr_network_analyst'),
        skillFolder('indie_monetization_strategist'),
        skillFolder('seo_visibility_expert'),
      ],
    },
    {
      type: 'category',
      label: 'Coaching & Personal Development',
      collapsed: false,
      items: [
        skillDoc('career_biographer'),
        skillFolder('cv_creator'),
        skillDoc('job_application_optimizer'),
        skillFolder('personal_finance_coach'),
        skillFolder('tech_entrepreneur_coach_adhd'),
        skillFolder('project_management_guru_adhd'),
        skillFolder('jungian_psychologist'),
        skillFolder('wisdom_accountability_coach'),
        skillFolder('hrv_alexithymia_expert'),
        skillFolder('speech_pathology_ai'),
        skillFolder('adhd_design_expert'),
      ],
    },
    {
      type: 'category',
      label: 'DevOps & Site Reliability',
      collapsed: false,
      items: [
        skillFolder('site_reliability_engineer'),
        skillFolder('code_necromancer'),
      ],
    },
  ],
};

export default sidebars;
